### PR TITLE
added mosdepth for coverage calculation

### PR DESCRIPTION
**Pull request by williamrowell**
Added a wrapper for mosdepth for coverage calculations.

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Thanks a lot! Please format with snakefmt (but check the comments, snakefmt sometimes still messes them up). For the test case, please add it to `test.py`, otherwise it won't be called.

**Comment by fgvieira** [comment]
Hi @williamrowell, any idea when you will add these changes?
It would be quite nice to have `mosdepth` added the wrappers.

**Comment by fgvieira** [comment]
@johanneskoester, I can add the test case to `test.py`. If you merge this PR, I'll take it from there and can do it this week.
Or how do you thing it is best to proceed?

**Comment by williamrowell** [comment]
Sorry, I've been swamped.  If you can point to a good test BAM, I'll add the test case this week.

**Comment by fgvieira** [comment]
It looks like you already have some BAM files in the wrapper, no?
I think that @johanneskoester meant that you need to add the tests to `test.py`, so that the wrapper gets actually tested.

**Comment by williamrowell** [comment]
@johanneskoester @fgvieira

Currently passes tests but fails linting because of the reserved term "prefix".  I used "prefix" because this is the name of the mosdepth parameter.  What is the preferred way of solving this?

**Comment by fgvieira** [comment]
I would

**Comment by williamrowell** [comment]
I agree with all except for the `prefix` fix, unless we switch to named outputs, since `{prefix}.mosdepth.summary.txt` seems to be the only output with a fixed name.  Other named outputs could be optional and not used by the wrapper.

```python
prefix = re.sub("\.mosdepth\.summary\.txt", "", snakemake.output.summary)
```

**Comment by fgvieira** [comment]
I agree, you can use named outputs and use `summary` to infer the prefix (just like you suggested).

**Comment by fgvieira** [comment]
@williamrowell, it would also be nice to have a `param` to specify precision, that is then passed to `mosdepth` as:
```
MOSDEPTH_PRECISION=5 mosdepth ...
```

**Comment by dlaehnemann** [comment]
It would definitely be nice to have mosdepth in here and thanks for all the work on this. Any time in the near-term future to pick this up, or would it be OK for me to pick this PR up and move it along?

**Comment by fgvieira** [comment]
I think you can move it along... as far as I can see, it is only missing to fix `prefix` and `MOSDEPTH_PRECISION`.
Let me know if there is anything I can help with.

**Review by dlaehnemann — APPROVED** [review]
OK, I think this is good to go. Added some more functionality and tests for everything. And all tests, including formatting and linting, are passing. :tada:

**Comment by williamrowell** [comment]
Thanks for picking this up.  I just didn't have time to add the rest of the features.

**Comment by dlaehnemann** [comment]
Yeah. I really like this tool, but its command line interface and file handling scheme requires quite a bit of fiddling, here...

**Review by johanneskoester — APPROVED** [review]

**Pull request merged**
