### PR TITLE
fix: Unpin minor version for cooltools wrappers

### PR DESCRIPTION
**Pull request by Phlya**

### CODE REVIEW

**Comment by Phlya** [comment]
I can't find it in the docs, is it possible for wrappers to share an environment? If multiple wrappers use the same tool, it would make sense...

**Comment by Phlya** [comment]
How is it possible that the environment for linting fails when it works for all other tests?..

**Comment by fgvieira** [comment]
Hi @Phlya, these changes might not be needed since, I think, there are some new GitHub actions that check for newer packages and update the environment.
Am I right @johanneskoester?

**Comment by Phlya** [comment]
I don't know about that, to be honest I encountered a bug that was fixed in the latest update, so wanted to avoid it by unpinning...

**Comment by Phlya** [comment]
Any more thoughts about this change?.. @fgvieira @johanneskoester

**Comment by johanneskoester** [comment]
Yes, unpinning is not the right way, wrappers are updated automatically by a bot. However, the cooltools wrappers all had wrong channel orders, which perhaps prevented the bot from determining how to update them. I've fixed that in PR https://github.com/snakemake/snakemake-wrappers/pull/980 which I would like to merge instead of this one. Nevertheless, thanks a lot for pointing to the issue and the first approach here.

**Comment by Phlya** [comment]
Oh I see, thank you for looking into it and fixing!

**Pull request closed without merging**
