### PR TITLE
added whatshap phase, haplotag, and stats commands

### PR DESCRIPTION
**Pull request by williamrowell**
WhatsHap is a tool to provide read-backed phasing of variants.  I have added wrappers for phase, haplotag, and stats subcommands.

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
thank you!

**Comment by dlaehnemann** [comment]
@johanneskoester @williamrowell These are still lacking test cases, if I am not mistaken?

**Comment by johanneskoester** [comment]
Oh sorry, my fault.

**Comment by johanneskoester** [comment]
@williamrowell I have reverted this PR. May I ask you to reopen it with test cases included?

**Pull request merged**
