### PR TITLE
added wrapper for samtools fasta/fastq

### PR DESCRIPTION
**Pull request by williamrowell**
Added wrapper for samtools fasta and samtools fastq.  Because the syntax is so similar, added "outputtype" param to specify output.

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Thanks a lot! Just one thing: I think the wrapper should be called `bio/samtools/fastx` which, in my experience seems to be the convention when referring to both fasta and fastq, instead of using an `n`.

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Further, please add a test case to `test.py`.

**Comment by williamrowell** [comment]
I've renamed this, updated, and added a test case.  It's ready for review.

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thank you!

**Pull request merged**
