### PR TITLE
Updates bwa-mem2 mem and index to v2.2.1

### PR DESCRIPTION
**Pull request by nikostr**
This PR updates bwa-mem2 to the latest version (v2.2.1) for the bwa-mem2/index and bwa-mem2/mem wrappers. This introduces a new, smaller, index.

### CODE REVIEW

**Comment by nikostr** [comment]
Ah, seems that #342 already addresses this!

**Comment by jafors** [comment]
If you add the version update in `bwa-mem2/samblaster`, we can merge this PR, since you already fixed the linting error the Snakefile in `bwa-mem2/index`.

**Comment by nikostr** [comment]
Thanks for reminding me, @jafors ! Should be sorted now :)

**Review by jafors — APPROVED** [review]
Great, thanks!

**Pull request merged**
