### PR TITLE
Implemented running MarkDuplicates on multiple bams.

### PR DESCRIPTION
**Pull request by brcopeland**
As noted in https://gatk.broadinstitute.org/hc/en-us/articles/360035889471-How-should-I-pre-process-data-from-multiplexed-sequencing-and-multi-library-designs- :

> 2. Merge read groups and mark duplicates per sample (aggregation + dedup)
> 
> Once you have pre-processed each read group individually, you merge read groups belonging to the same sample into a single BAM file. You can do this as a standalone step, bur for the sake of efficiency we combine this with the per-sample duplicate marking step (it's simply a matter of passing the multiple inputs to MarkDuplicates in a single command).

### CODE REVIEW

**Comment by jafors** [comment]
In the updated wrapper, the `-I {input}` is indeed used instead of `--INPUT={input}`.
But maybe we should update the version in the environment.yaml (should be 2.25.0 at the moment) and use the "new" syntax throughout.

**Comment by brcopeland** [comment]
Could you clarify where the `-I` is for me?  I've been trying to figure this out; I looked at https://github.com/snakemake/snakemake-wrappers/blob/master/bio/picard/markduplicates/wrapper.py which is what I believe it would be accessing.

**Comment by brcopeland** [comment]
I made another small change because I was experiencing what I perceived as a bug; the wrapper previously passed all `params` (interpreting these as "extra") along to picard instead of only `params.extra`.  I think this is the intended functionality.

**Comment by jafors** [comment]
> I made another small change because I was experiencing what I perceived as a bug; the wrapper previously passed all `params` (interpreting these as "extra") along to picard instead of only `params.extra`. I think this is the intended functionality.

Good thinking, but in this case, since `params` does not have a field `extra` in the example Snakefile, this would not include the given parameters. I think until there is no need for a parameter to be distinct from the rest (so you would need to have `params.extra` and `params.xyz`) , I would leave it as it was to not introduce a breaking change for people not using `params.extra` but just `params`.
When creating new wrappers though, I would suggest always using `extra` as a `params` field, it just looks "cleaner" to me.

**Comment by brcopeland** [comment]
I could change that back but it would definitely break things for me; you can see in the current version all `params` are passed as `extra`, but this includes `params.java_opts`, which are then parsed and again passed in.

Additionally I am working on a PBS/TORQUE cluster and based my cluster profile on https://github.com/Snakemake-Profiles/pbs-torque/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/pbs-submit.py .  I recognize this may not be an optimal solution, but at line 139 there, I couldn't define `cluster` within a rule so I changed this to look in `params` instead.  The way this wrapper is written now passes on these additional parameters.

**Comment by jafors** [comment]
Okay, didn't think about this, you are definitely correct! That's a pretty big reason for defining `params.extra`.

**Review by jafors — APPROVED** [review]

**Pull request merged**
