### PR TITLE
VEP cache with fully specified output folder with wildcards

### PR DESCRIPTION
**Pull request by fgvieira**
Implementation of #236, where the output folder has to be fully specified (including the part that is added by the ensembl script),  so that the outptut can be checked by the rule if it exists or not.

This way, we can specify the specific cache for a given species/build/release and check if it exists.

### CODE REVIEW

**Comment by johanneskoester** [comment]
If I am not completely misunderstanding something, I don't think this PR is needed. Specifying species and release in the wildcards is already possible now: 
```
rule get_vep_cache:
    output:
        directory("resources/vep/cache/{species}/{release}_{build}")
    params:
        species=lambda w: w.species,
        build=lambda w: w.build,
        release=lambda w: w.release,
    log:
        "logs/vep/cache/{species}/{release}_{build}.log"
    cache: True  # save space and time with between workflow caching (see docs)
    wrapper:
        "master/bio/vep/cache"
```

In other words, the current wrapper is usable in both ways:
1. one species, build, release per workflow (hence no need for the wildcards).
2. multiple species, build, release in one workflow (encoding via wildcards).

**Comment by johanneskoester** [comment]
Please reopen if I did not correctly understand this.

**Comment by johanneskoester** [comment]
And, in any case, still thanks a lot for taking the time to work on this! What we could easily do is to add above example to the current wrapper.

**Comment by fgvieira** [comment]
Yes, you could include the wildcards but the output folder would actually end up being `resources/vep/cache/{species}/{release}_{build}/{species}/{release}_{build}`, since the `ensembl-vep` cache script creates extra folders. I guess it is not that critical, just a bit redundant.. :smile: 

And how would that play out with the snakemake `cache`, if there are no wildcards?

**Comment by johanneskoester** [comment]
> Yes, you could include the wildcards but the output folder would actually end up being `resources/vep/cache/{species}/{release}_{build}/{species}/{release}_{build}`, since the `ensembl-vep` cache script creates extra folders. I guess it is not that critical, just a bit redundant.. smile
True, but you don't see that, and consuming vep wrappers handle that correctly.

> And how would that play out with the snakemake `cache`, if there are no wildcards?

The cache hashes params, code and software stack. It does not hash wildcards (as people can name them differently). Hence, it is even crucial to have these encoded in params.

**Pull request closed without merging**
