### PR TITLE
chm_eval: remove symlink to chm_eval_kit output that does not exist in repo

### PR DESCRIPTION
**Pull request by dlaehnemann**
This seems like the current reason for tests still failing on the master branch.

### CODE REVIEW

**Comment by dlaehnemann** [comment]
Hmm, the `chm_eval` test is also using the `chm_eval_kit` wrapper to get input input data, but doesn't seem to be able to load the other wrapper properly, as its data is not copied alongside `chm_eval`'s data. Can we somehow use the standard snakemake way of deploying wrappers for this test?

**Comment by johanneskoester** [comment]
Fixed in commit 1c800958654163da4b372bfec3cc4e59e52c6698

**Comment by johanneskoester** [comment]
Thank you anyway!

**Comment by dlaehnemann** [comment]
Cheers for the cleanup!

**Pull request closed without merging**
