### PR TITLE
Add samtools-depth

### PR DESCRIPTION
**Pull request by daynefiler**
Hi, 

I tried to do some testing on this, because I am not sure the optional bed portion was implemented correctly. I kept running into issues with conda and could not do full testing.

### CODE REVIEW

**Comment by daynefiler** [comment]
I keep running into environment creation failures when trying to test locally.

    (snakemake) [14:50]dayne:test$ snakemake --snakefile Snakefile --use-conda --wrapper-prefix "https://github.com/daynefiler/snakemake-wrappers/tree/"
    Building DAG of jobs...
    Creating conda environment https:/github.com/daynefiler/snakemake-wrappers/tree/master/bio/samtools/depth/environment.yaml...
    Downloading and installing remote packages.
    CreateCondaEnvironmentException:
      Could not create conda environment from /var/folders/yb/9clrgrjd3_j7d15sf25n05300000gn/T/tmp5wq202yl.yaml:
      
      # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
      
      Traceback (most recent call last):
      File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 80, in execute
    directory=os.getcwd())
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 40, in detect
    if spec.can_handle():
      File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
    self._environment = env.from_file(self.filename)
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 151, in from_file
    return from_yaml(yamlstr, filename=filename)
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 136, in from_yaml
    data = yaml_load_standard(yamlstr)
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
    return yaml.load(string, Loader=yaml.Loader, version="1.2")
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 99, in compose_document
    self.parser.get_event()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 166, in get_event
    self.current_event = self.state()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 244, in parse_document_end
    token = self.scanner.peek_token()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 173, in peek_token
    self.fetch_more_tokens()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 273, in fetch_more_tokens
    return self.fetch_value()
    File "/Users/dayne/miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 626, in fetch_value
    self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
    in "<unicode string>", line 114, column 71:
      ... r-bar top-0 left-0" style="width: 0%;"></span>
                                                 ^ (line: 114)
    
    `$ /Users/dayne/miniconda3/bin/conda-env create --file /Users/dayne/Github/snakemake-wrappers/bio/samtools/depth/test/.snakemake/conda/ba726334.yaml --prefix /Users/dayne/Github/snakemake-wrappers/bio/samtools/depth/test/.snakemake/conda/ba726334`
    
      environment variables:
                     CIO_TEST=<not set>
      CONDA_AUTO_UPDATE_CONDA=false
              CONDA_BACKUP_AR=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-ar
              CONDA_BACKUP_AS=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-as
              CONDA_BACKUP_CC=x86_64-apple-darwin13.4.0-clang
          CONDA_BACKUP_CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE
                              -fstack-protector-strong -O2 -pipe -I/include -fdebug-prefix-
                              map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION}
                              -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
       CONDA_BACKUP_CHECKSYMS=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-checksyms
           CONDA_BACKUP_CLANG=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-clang
         CONDA_BACKUP_CLANGXX=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-clang++
    CONDA_BACKUP_CODESIGN_ALLOCATE=/Users/dayne/miniconda3/bin/x86_64-apple-
                              darwin13.4.0-codesign_allocate
    CONDA_BACKUP_CONDA_BUILD_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/D
                              eveloper/SDKs/MacOSX.sdk
        CONDA_BACKUP_CPPFLAGS=-D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9
             CONDA_BACKUP_CXX=x86_64-apple-darwin13.4.0-clang++
        CONDA_BACKUP_CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE
                              -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-
                              inlines-hidden -std=c++14 -fmessage-length=0 -I/include -fdebug-
                              prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION}
                              -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
    CONDA_BACKUP_DEBUG_CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE
                              -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -I/include
                              -fdebug-prefix-
                              map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION}
                              -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
    CONDA_BACKUP_DEBUG_CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE
                              -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-
                              inlines-hidden -std=c++14 -fmessage-length=0 -Og -g -Wall -Wextra
                              -I/include -fdebug-prefix-
                              map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION}
                              -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
    CONDA_BACKUP_DEBUG_FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector
                              -O2 -pipe -march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-
                              protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace
                              -fimplicit-none -fvar-tracking-assignments
          CONDA_BACKUP_FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector
                              -O2 -pipe
    CONDA_BACKUP_FORTRANFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector
                              -O2 -pipe
        CONDA_BACKUP_GFORTRAN=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-gfortran
            CONDA_BACKUP_HOST=x86_64-apple-darwin13.4.0
            CONDA_BACKUP_INDR=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-indr
    CONDA_BACKUP_INSTALL_NAME_TOOL=/Users/dayne/miniconda3/bin/x86_64-apple-
                              darwin13.4.0-install_name_tool
              CONDA_BACKUP_LD=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-ld
         CONDA_BACKUP_LDFLAGS=-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs
                              -Wl,-rpath,/lib -L/lib
      CONDA_BACKUP_LDFLAGS_LD=-pie -headerpad_max_install_names -dead_strip_dylibs -rpath /lib
                              -L/lib
         CONDA_BACKUP_LIBTOOL=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-libtool
            CONDA_BACKUP_LIPO=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-lipo
              CONDA_BACKUP_NM=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-nm
          CONDA_BACKUP_NMEDIT=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-nmedit
           CONDA_BACKUP_OTOOL=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-otool
       CONDA_BACKUP_PAGESTUFF=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-pagestuff
          CONDA_BACKUP_RANLIB=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-ranlib
    CONDA_BACKUP_REDO_PREBINDING=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-redo_prebinding
         CONDA_BACKUP_SEGEDIT=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-segedit
    CONDA_BACKUP_SEG_ADDR_TABLE=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-seg_addr_table
        CONDA_BACKUP_SEG_HACK=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-seg_hack
            CONDA_BACKUP_SIZE=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-size
         CONDA_BACKUP_STRINGS=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-strings
           CONDA_BACKUP_STRIP=/Users/dayne/miniconda3/bin/x86_64-apple-darwin13.4.0-strip
    CONDA_BACKUP__CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_apple_darwin13_4_0
                  CONDA_BUILD=1
            CONDA_DEFAULT_ENV=snakemake
                    CONDA_EXE=/Users/dayne/miniconda3/bin/conda
                 CONDA_PREFIX=/Users/dayne/miniconda3/envs/snakemake
               CONDA_PREFIX_1=/Users/dayne/miniconda3
        CONDA_PROMPT_MODIFIER=(snakemake)
             CONDA_PYTHON_EXE=/Users/dayne/miniconda3/bin/python
                   CONDA_ROOT=/Users/dayne/miniconda3
                  CONDA_SHLVL=2
                         PATH=/Users/dayne/miniconda3/envs/snakemake/bin:/Users/dayne/miniconda3/con
                              dabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bi
                              n:/Library/TeX/texbin:/opt/X11/bin:/Users/dayne/miniconda3/bin:/Users/
                              dayne/bin:/Users/dayne/bin/flutter/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : snakemake
        active env location : /Users/dayne/miniconda3/envs/snakemake
                shell level : 2
           user config file : /Users/dayne/.condarc
     populated config files : /Users/dayne/.condarc
              conda version : 4.8.2
        conda-build version : 3.18.11
             python version : 3.6.7.final.0
           virtual packages : __osx=10.15.3
           base environment : /Users/dayne/miniconda3  (writable)
               channel URLs : https://conda.anaconda.org/bioconda/osx-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://conda.anaconda.org/conda-forge/osx-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://repo.anaconda.com/pkgs/main/osx-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/osx-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /Users/dayne/miniconda3/pkgs
                              /Users/dayne/.conda/pkgs
           envs directories : /Users/dayne/miniconda3/envs
                              /Users/dayne/.conda/envs
                   platform : osx-64
                 user-agent : conda/4.8.2 requests/2.18.4 CPython/3.6.7 Darwin/19.3.0 OSX/10.15.3
                    UID:GID : 501:20
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    
    If submitted, this report will be used by core maintainers to improve
    future releases of conda.
    Would you like conda to send this report to the core maintainers?
    
    [y/N]: 
    Timeout reached. No report sent.
    
    
      File "/Users/dayne/miniconda3/envs/snakemake/lib/python3.6/site-packages/snakemake/deployment/conda.py", line 314, in create

**Comment by johanneskoester** [comment]
Thanks! Please add a test function to `test.py` analogous to the other samtools wrappers.

**Comment by daynefiler** [comment]
@johanneskoester I added the test & ran the script -- it did not give any output which I am hoping means the test worked.

**Comment by daynefiler** [comment]
@johanneskoester Finally got it! Sorry for all of the commits -- still learning the snakemake ropes. And next time I'll make a separate branch.

**Comment by daynefiler** [comment]
Squashed my mess of commits into a single clean commit.

**Comment by daynefiler** [comment]
Going to close & re-open from a clean branch so that I can add other PRs.

**Pull request closed without merging**
