### PR TITLE
feat: implement fragment size as optional input file

### PR DESCRIPTION
**Pull request by ftabaro**
### Description

Addresses #1238 

### QC

* [x ] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

### CODE REVIEW

**Comment by fgvieira** [comment]
It seems `extsize` (or `fragsize`) is a single integer, no? If so, I feel if would make more sense to be a `param`.
Would it make sense to define it as a param and define a function that reads the input file? For example, define a function that returns `extsize`:
```
def get_frag_size(in_fragsize):
    with open(in_fragsize) as handler:
        return handler.readline().strip()
```
and call it in `params` as:
```
rule foo:
[...]
params:
    extsize = lambda w, input: get_frag_size(input.fragsize)
```
or even:
```
rule foo:
[...]
params:
    extra = lambda w, input: "--extsize {}".format(get_frag_size(input.fragsize))
```

**Comment by ftabaro** [comment]
Hi, thanks! Yes that would make sense. But how to make the callpeak rule depend on upstream rule(s) that compute this integer? For instance, using the `csaw` R package, one could print the value to stdout. However, currently we save it to a file and require such file as input for downstream rules. Will reading the file in a functions within  params make it required for the target rule (here macs2 callpeak)?

**Comment by fgvieira** [comment]
> Will reading the file in a functions within params make it required for the target rule (here macs2 callpeak)?

No, but you can add the file to the rule's input function.

You can keep the rules as you have now: first rule estimates parameter and writes into file, while second rule takes output of previous rule as input and calls peaks:
```
def get_frag_size(in_fragsize):
    with open(in_fragsize) as handler:
        return handler.readline().strip()

rule csaw:
    input:
        [...]
    output:
        "csaw.out"

rule call_peak:
    input:
        fragsize = "csaw.out"
    output:
        "peaks.out"
    params:
        extra = lambda w, input: "--extsize {}".format(get_frag_size(input.fragsize))
```

**Comment by ftabaro** [comment]
Do you think it would make sense to have this implemented in the wrapper?

**Pull request closed without merging**
