### PR TITLE
feat: gbasf2_wrapper

### PR DESCRIPTION
**Pull request by casschmitt**
### Description

Adding a wrapper called gbasf2, enabeling snakemake to submit rules as jobs to the Belle II grid, similar to the LHC Computing Grid. Intended to be used for workflows on the KEKcc computing cluster only.

PS: Input file paths to the Belle II grid are always absolute, which gives an unavoidable warning in snakemake linting.

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

### CODE REVIEW

**Comment by fgvieira** [comment]
Is this wrapper intended to submit jobs to a specific cluster?
if so, why not use snakemake profiles (e.g. [here](https://github.com/orgs/Snakemake-Profiles/repositories))?

**Comment by casschmitt** [comment]
As indicated above:
"Input file paths to the Belle II grid are always absolute, which gives an unavoidable warning in snakemake linting."
Is there a way to circumvent the failed linting check above? Thank you.

**Comment by casschmitt** [comment]
> Is this wrapper intended to submit jobs to a specific cluster? if so, why not use snakemake profiles (e.g. [here](https://github.com/orgs/Snakemake-Profiles/repositories))?

I am not using a profile, since only some rules need to be submitted to the cluster and not all rules of a typical Belle II workflow. With a wrapper, I can specify per rule what goes on the cluster.

**Comment by fgvieira** [comment]
The rules that are not submitted to the cluster, are they intended to be run locally? Because if so, they could be defined as [local rules](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#local-rules).

**Comment by casschmitt** [comment]
> The rules that are not submitted to the cluster, are they intended to be run locally? Because if so, they could be defined as [local rules](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#local-rules).

In a typical Belle II workflow, we have 3 types of rules. The ones that run on our dedicated cluster (with the wrapper), the ones that run on a qsub cluster (--cluster qsub) and the ones that run locally (localrules). This is the only way I was able to implement it in a snakemake workflow and it works very nicely.

PS: To circumvent the linting error, I could read in the absolute path from a separate file. Would this be preferred? Thank you

**Comment by fgvieira** [comment]
From what you are saying, it seems like you'd like to be able to specify rule-specific profiles. If so, then I think the best way would be to do it through `snakemake`, and not through a wrapper. This would be quite neat, as it would allow `snakemake` to work with an arbitrary number (and type) of clusters.

@johanneskoester what do you think?

**Comment by casschmitt** [comment]
> From what you are saying, it seems like you'd like to be able to specify rule-specific profiles. If so, then I think the best way would be to do it through `snakemake`, and not through a wrapper. This would be quite neat, as it would allow `snakemake` to work with an arbitrary number (and type) of clusters.
> 
> @johanneskoester what do you think?
 
Rule-specific profiles would be very nice. For now though, we might use the wrapper and make it publicly available for analysts? Once rule-specific profiles are available in snakemake, we could transfer to a profile.

**Comment by casschmitt** [comment]
Dear all, I moved the absolute path into a separate file. In this way snakemake linting throws no warnings. Is there any updated opinion on this merge? Thank you

**Comment by casschmitt** [comment]
It's been two weeks and I am trying to provide this wrapper to collaborators. Are there any updates on how to proceed @johanneskoester @fgvieira? Thank you.

**Comment by casschmitt** [comment]
Dear all, as far as I know the snakemake wrapper repository does not come with GPL3 compatible license. However, it turns out that some collaborators require this. Therefore I will close this pull request and publish the wrapper elsewhere with GPL3 compatible license. Thank you for your help nevertheless!

**Pull request closed without merging**
