### PR TITLE
feat: added vsearch wrapper

### PR DESCRIPTION
**Pull request by fgvieira**
### Description

Added wrapper for VSEARCH.

### QC

* [x] I confirm that:

For all wrappers added by this PR, 

* there is a test case which covers any introduced changes,
* `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* the `meta.yaml` contains a link to the documentation of the respective tool or command,
* `Snakefile`s pass the linting (`snakemake --lint`),
* `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* Python wrapper scripts are formatted with [black](https://black.readthedocs.io).
* Conda environments use a minimal amount of channels, in recommended ordering. E.g. for bioconda, use (conda-forge, bioconda, nodefaults, as conda-forge should have highest priority and defaults channels are usually not needed because most packages are in conda-forge nowadays).

### CODE REVIEW

**Review by johanneskoester — CHANGES_REQUESTED** [review]
I think we should avoid the out_arg necessity and just infer the required args from the output file extension. And then, I would just have an extra param for additional args instead of fasta_arg and fastq_arg.

**Comment by fgvieira** [comment]
Added automated output inference.

**Comment by johanneskoester** [comment]
What about the fasta_arg and fastq_arg? Can't people just use extra for that?

**Comment by fgvieira** [comment]
I think the way I did for `outputs` could also work for `inputs`... what do you think?

**Review by dlaehnemann — APPROVED** [review]
Looks good to me, very thorough work!

**Review by johanneskoester — APPROVED** [review]

**Pull request merged**
