### PR TITLE
fix: Nextflow profile

### PR DESCRIPTION
**Pull request by tpall**
### Description

- Fixed bug where Nextflow *-profile* option was inserted also second time with double hyphens (--profile ..) to nextflow call. 
- Added snakemake *extra* parameter to pass other single hyphen options to nextflow (e.g. -resume []).
- Removed nextflow version from environment file.

All these have been tested by running nf-core/mag pipeline.

### QC

For all wrappers added by this PR, I made sure that

* [ ] there is a test case which covers any introduced changes,
* [ ] `input:` and `output:` file paths in the resulting rule can be changed arbitrarily,
* [ ] either the wrapper can only use a single core, or the example rule contains a `threads: x` statement with `x` being a reasonable default,
* [ ] rule names in the test case are in [snake_case](https://en.wikipedia.org/wiki/Snake_case) and somehow tell what the rule is about or match the tools purpose or name (e.g., `map_reads` for a step that maps reads),
* [ ] all `environment.yaml` specifications follow [the respective best practices](https://stackoverflow.com/a/64594513/2352071),
* [ ] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`),
* [ ] all fields of the example rules in the `Snakefile`s and their entries are explained via comments (`input:`/`output:`/`params:` etc.),
* [ ] `stderr` and/or `stdout` are logged correctly (`log:`), depending on the wrapped tool,
* [ ] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to (see [here](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir); this also means that using any Python `tempfile` default behavior works),
* [ ] the `meta.yaml` contains a link to the documentation of the respective tool or command,
* [ ] `Snakefile`s pass the linting (`snakemake --lint`),
* [ ] `Snakefile`s are formatted with [snakefmt](https://github.com/snakemake/snakefmt),
* [ ] Python wrapper scripts are formatted with [black](https://black.readthedocs.io).

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Can you please reformat your changes with black?

**Comment by fgvieira** [comment]
Are you using the latest `black` version? According to #460, GitHub Runners use version `22.1.0`.

**Comment by johanneskoester** [comment]
You also need to format other wrappers (maybe just bad luck, sorry):
```
black bio/gatk/applybqsrspark/wrapper.py bio/biobambam2/bamsormadup/wrapper.py
```

**Comment by fgvieira** [comment]
Those formatting issues have already been fixed in `master`, so just rebase your branch to the current `master`.

**Comment by tpall** [comment]
I was using `black` version `21.6b0`, but version `22.1.0` was happy too.

**Comment by johanneskoester** [comment]
Thanks!

**Pull request merged**
