### PR TITLE
chore: remove wrapper for unmaintained `nanosim-h` in favor of new `nanosim` wrapper (#3165)

### PR DESCRIPTION
**Pull request by dlaehnemann**
### QC

* [x] I confirm that I have followed the [documentation for contributing to `snakemake-wrappers`](https://snakemake-wrappers.readthedocs.io/en/stable/contributing.html).

While the contributions guidelines are more extensive, please particularly ensure that:
* [x] `test.py` was updated to call any added or updated example rules in a `Snakefile`
* [x] `input:` and `output:` file paths in the rules can be chosen arbitrarily
* [x] wherever possible, command line arguments are inferred and set automatically (e.g. based on file extensions in `input:` or `output:`)
* [x] temporary files are either written to a unique hidden folder in the working directory, or (better) stored where the Python function `tempfile.gettempdir()` points to 
* [x] the `meta.yaml` contains a link to the documentation of the respective tool or command under `url:`
* [x] conda environments use a minimal amount of channels and packages, in recommended ordering

## Summary by CodeRabbit

- **New Features**
	- Enhanced the simulator's configuration with a new URL linking to the project's GitHub repository.
	- Expanded the parameters section with detailed descriptions for command line arguments, improving clarity for users.
	- Added a `max_read_len` parameter to the `nanosimh` rule, allowing for longer simulated reads.

- **Improvements**
	- Reformatted the description in the configuration file for better readability.
	- Improved input handling in the simulation function for enhanced flexibility.

- **Bug Fixes**
	- Updated parameter handling to ensure correct execution of commands with new inputs.
	- Removed outdated test function to streamline testing strategy.

### CODE REVIEW

**Comment by fgvieira** [comment]
Just wondering what the advantage would be of having all parameters separately (instead of a single `params.extra`).

**Comment by dlaehnemann** [comment]
Yeah, I also saw that. Also, it might make sense to run stuff in a temporary directory and then copy to truly arbitrary file path and names. But I think I think it is not worth investing too much in this wrapper, as `nanosim-h` does not seem to be maintained any further, with the last commit 3 years ago today:
https://github.com/karel-brinda/NanoSim-H/commit/093831e2b9c60a79f9a576e93366ac92c4c46a11

So for my own usage, I am now working on a wrapper for the original tool, `nanosim`, which is being maintained and has more functionality nowadays. For that one, I am opting for an only `extra=`-based command line argument handling (apart from file-extension based auto-inferences and the likes). But I'll fix the formatting here, later today, so that we can at least improve this wrapper a bit, while I am at it...

**Comment by dlaehnemann** [comment]
Just fixed the formatting, so I hope all tests will run through, now. Feel free to review and merge, if you are satisfied, @fgvieira.

Also, the [newer `nanosim` wrapper is finally in a PR](https://github.com/snakemake/snakemake-wrappers/pull/3165) as well, in case you feel like reviewing a wrapper that works around a veeeery quirky command-line interface and some interesting choices for configuration files...

**Comment by dlaehnemann** [comment]
Hmm, I can't seem to get `nanosim-h` to run in the tests, neither in the CI, nor locally. I think I'll just cut my losses and retire this PR in favor of the new `nanosim` wrapper.

Should we maybe remove this old wrapper altogether? It will still exist in the older `snakemake-wrapper` releases, but people will not start using this unmaintained tool (and wrapper), simply because they find it on the docs...

**Comment by fgvieira** [comment]
Yep, if we cannot get it to work and @johanneskoester has nothing against it, I agree that it is better to just remove it.

**Comment by dlaehnemann** [comment]
Maybe I'll try to summon @mbhall88, who originally create the wrapper. Michael, would you have anything against retiring this wrapper and instead only listing the new `nanosim` wrapper from #3165 ?

**Comment by mbhall88** [comment]
> Maybe I'll try to summon @mbhall88, who originally create the wrapper. Michael, would you have anything against retiring this wrapper and instead only listing the new `nanosim` wrapper from #3165 ?

Fine by me

**Review by fgvieira — APPROVED** [review]

**Pull request merged**
